### PR TITLE
Add cluster-metrics monitoring stack

### PR DESCRIPTION
**Pull request by ldcastell**
This commit adds the "cluster-metrics" monitoring stack
which original code is at:
https://github.com/openstack/openstack-ansible-ops/tree/master/cluster_metrics

This commit also simplifies the installation process by just
having a shell script run the needed commands

### CODE REVIEW

**Comment by mwturvey** [comment]
Is this initial commit an exact copy of what is in that other branch, or is a copy plus a bunch of your changes?

**Comment by ldcastell** [comment]
it is a copy plus some changes regarding the installation process @mwturvey

**Comment by mwturvey** [comment]
Can you make the first commit an exact copy of the other repo?  That way if we ever want to merge their future changes into this repo, it will be much easier.  (i.e. you can effectively make a branch off of the original commit to this repo, apply the changes from the official repo, then merge back in).  

Specifically, make the original commit in this repo the _exact_ version from the other repo that your changes have started from.

**Comment by ChristopherMSpencer** [comment]
In the future it would be nice to see those changes in two separate PRs.  One being the fork/merge of code that isn't ours (so I don't have to review other people's working (hopefully) code) and can focus on what your changes are in the 2nd review

**Comment by ldcastell** [comment]
Closing this PR. Need to commit the fork from the original repo first

**Pull request closed without merging**
